### model
model_name_or_path: /home/dataset-local/lkl/models/Qwen3-VL-8B-Instruct
image_max_pixels: 802816
video_max_pixels: 100352
video_maxlen: 128
video_fps: 2
trust_remote_code: true
disable_gradient_checkpointing: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
deepspeed: LLaMA-Factory/examples/deepspeed/ds_z3_8gpu.json

### dataset
dataset: onethinker_sft_visual_cot_3step_core,onethinker_sft_gqa_visual_cot_30k_mixed,onethinker_sft_image_nogrounding
template: qwen3_vl
dataset_dir: /home/dataset-local/lkl/datasets/CoLT_Train_Dataset
media_dir: /home/dataset-local/lkl/datasets/CoLT_Train_Dataset
mix_strategy: interleave_over
interleave_probs: "0.4465,0.1535,0.4000"
use_fast_tokenizer: false
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 32
preprocessing_batch_size: 32
max_samples: 2000
tokenized_path: /home/dataset-local/lkl/cache/colt/visual_cot_v2_base_mixed_rerun_smoke_tokenized

### output
output_dir: /home/dataset-local/lkl/CoLT-reproduction/checkpoints/colt_paper_faithful_visual_cot_v2_base_mixed_rerun_smoke
logging_steps: 1
save_steps: 100
save_strategy: steps
save_only_model: false
plot_loss: true
overwrite_output_dir: false
save_total_limit: 2

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
weight_decay: 1.0e-6
num_train_epochs: 1.0
max_steps: 100
lr_scheduler_type: cosine
warmup_ratio: 0.02
bf16: true
ddp_timeout: 180000000
flash_attn: fa2

### eval
report_to: wandb
run_name: colt_sft_8b_lkl_8gpu_visual_cot_v2_base_mixed_rerun_smoke
